/**
 * NarrativeViewer
 *
 * Displays the Conservative and Exploratory career narrative documents
 * generated by narrative_synthesizer.py.
 *
 * The Exploratory tab shows a warning banner (per the tool design: not for
 * automated embedding, for human review only).
 */

import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { getNarratives } from '../services/api';
import './NarrativeViewer.css';

/** Strip YAML front matter (--- ... ---) from markdown content. */
function stripFrontMatter(content) {
  if (!content) return '';
  const parts = content.split('---');
  if (parts.length >= 3) {
    return parts.slice(2).join('---').trim();
  }
  return content.trim();
}

/** Trigger a .md file download in the browser without a new endpoint. */
function downloadMarkdown(content, filename) {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

const NarrativeViewer = ({ sessionId, pipelineStatus }) => {
  const [activeTab, setActiveTab]   = useState('conservative');
  const [narratives, setNarratives] = useState({ conservative: null, exploratory: null });
  const [loading, setLoading]       = useState(false);
  const [error, setError]           = useState('');

  const hasNarratives =
    pipelineStatus?.narratives_conservative || pipelineStatus?.narratives_exploratory;

  // Load narratives when they become available or session changes
  useEffect(() => {
    if (!sessionId || !hasNarratives) return;

    const load = async () => {
      setLoading(true);
      setError('');
      try {
        const data = await getNarratives(sessionId);
        setNarratives({
          conservative: data.conservative || null,
          exploratory:  data.exploratory  || null,
        });
      } catch (err) {
        setError(err.response?.data?.error || err.message);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [sessionId, pipelineStatus?.narratives_conservative, pipelineStatus?.narratives_exploratory]); // eslint-disable-line react-hooks/exhaustive-deps

  if (!hasNarratives) {
    return (
      <div className="narrative-viewer narrative-empty">
        <div className="narrative-placeholder">
          <span className="narrative-placeholder-icon">📖</span>
          <h3>No Narratives Yet</h3>
          <p>
            Complete <strong>Step 1 — Analyze Graph</strong> first, then run
            <strong> Step 2 — Generate Narratives</strong> in the Analysis
            Pipeline sidebar.
          </p>
          <p className="narrative-hint">
            Narrative synthesis makes 2 LLM calls and takes ~30 seconds.
          </p>
        </div>
      </div>
    );
  }

  if (loading) {
    return <div className="narrative-viewer narrative-loading"><p>Loading narratives…</p></div>;
  }

  if (error) {
    return <div className="narrative-viewer narrative-error"><p>⚠ {error}</p></div>;
  }

  const content = narratives[activeTab];
  const filename = `career_narrative_${activeTab}.md`;

  return (
    <div className="narrative-viewer">
      {/* Tab strip */}
      <div className="narrative-tabs">
        <button
          className={`narrative-tab ${activeTab === 'conservative' ? 'active' : ''} ${narratives.conservative ? '' : 'unavailable'}`}
          onClick={() => setActiveTab('conservative')}
        >
          {narratives.conservative ? '✓ ' : '○ '}Conservative
        </button>
        <button
          className={`narrative-tab ${activeTab === 'exploratory' ? 'active' : ''} ${narratives.exploratory ? '' : 'unavailable'}`}
          onClick={() => setActiveTab('exploratory')}
        >
          {narratives.exploratory ? '✓ ' : '○ '}Exploratory
        </button>

        {content && (
          <button
            className="narrative-download-btn"
            onClick={() => downloadMarkdown(content, filename)}
            title={`Download ${filename}`}
          >
            📥 Download .md
          </button>
        )}
      </div>

      {/* Exploratory warning banner */}
      {activeTab === 'exploratory' && narratives.exploratory && (
        <div className="narrative-warning">
          ⚠ <strong>Exploratory version:</strong> This narrative may infer,
          hypothesize, and suggest. It is for human review only — do not embed
          in automated systems. Every observation still cites a source analysis.
        </div>
      )}

      {/* Content */}
      <div className="narrative-content">
        {content ? (
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {stripFrontMatter(content)}
          </ReactMarkdown>
        ) : (
          <div className="narrative-not-available">
            <p>This narrative version was not generated.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default NarrativeViewer;
